showNavigation: true
logLevel: "INFO"
showNewVersions: false
showFooter: true



entities:
  # - file: /etc/OliveTin/containers.json
  #   name: container

  - file: /etc/OliveTin/servers.yaml
    name: server

actions:
  - title: "Start Ouster Lidar"
    shell: ssh -i /config/ssh/id_rsa bjoern@192.168.0.2 "cd ~/git/go1-ros-melodic && docker compose up ouster"
    icon: '<img src = "customIcons/nav2_start.png" width = "48px"/>'
  - title: "Stop Ouster Lidar"
    shell: ssh -i /config/ssh/id_rsa bjoern@192.168.0.2 "cd ~/git/go1-ros-melodic && docker compose stop ouster"
    icon: '<img src = "customIcons/nav2_stop.png" width = "48px"/>'
  - title: "Start Realsense"
    shell: ssh -i /config/ssh/id_rsa bjoern@192.168.0.2 "cd ~/git/go1-ros-melodic && docker compose up realsense"
    icon: '<img src = "customIcons/mapping_start.gif" width = "48px"/>'
  - title: "Stop Realsense"
    shell: ssh -i /config/ssh/id_rsa bjoern@192.168.0.2 "cd ~/git/go1-ros-melodic && docker compose stop realsense"
    icon: '<img src = "customIcons/mapping_stop.gif" width = "48px"/>'
  # - title: "Restart Teleop"
  #   icon: '<img src = "customIcons/gamepad.png" width = "48px"/>'
  #   shell: docker restart cps_loki-teleop-1
  - title: Restart or Shutdown System
    icon: restart
    shell: ssh -i /config/ssh/id_rsa bjoern@192.168.0.2 "cd ~/git/go1-ros-melodic && systemctl {{ choice }}" 
    arguments:
      - name: choice
        title: Pick one
        choices:
          - value: reboot
          - value: shutdown
  # This will SSH into a server an run the command "echo complete"
  - title: SSH test
    shell: ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=no bjoern@192.168.20.79 "echo complete"
    icon: ping
    timeout: 5

  - title: SSH docker start ouster
    shell: ssh -i /config/ssh/id_rsa bjoern@192.168.20.79 "cd ~/git/go1-ros-melodic && docker compose up ouster"
    icon: ping
    timeout: 5
